package ait.cohort34.accounting.dto.exceptions;

public class UserNotFoundException extends RuntimeException {
}
